Correct path Turn off sloth Install the correct version of Boost Fix location

diff --git a/Dockerfile.production-pw b/Dockerfile.production-pw
--- a/Dockerfile.production-pw
+++ b/Dockerfile.production-pw
@@ -2,9 +2,8 @@ FROM registry.sh.nextgenwaterprediction.com/infrastructure/rockylinux/rockylinux
 
 # Install runtime dependencies
 RUN set -eux; \
-    dnf install -y yum-utils; \
+    dnf install -y yum-utils epel-release; \
     dnf config-manager --set-enabled crb; \
-    dnf install -y epel-release; \
     dnf install -y \
         file \
         findutils \
@@ -16,8 +15,24 @@ RUN set -eux; \
         python3.11-pip \
         python3.11-setuptools \
         singularity-ce \
-        which; \
+        # The following needed for partitionGenerator
+        make \
+        gcc-c++ \
+        sqlite-devel \
+        cmake \
+        udunits2 udunits2-devel; \
     dnf clean all
+
+# Install Boost 1.79.0 from source
+ARG BOOST_VERSION=1.79.0
+RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-boost \
+    set -eux; \
+    curl --location --output boost.tar.gz "https://archives.boost.io/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz"; \
+    mkdir -p /opt/boost && \
+    tar --extract --directory /opt/boost --strip-components=1 --file boost.tar.gz && \
+    rm boost.tar.gz
+
+ENV BOOST_ROOT=/opt/boost
 
 # Install Docker CLI
 RUN dnf -y install dnf-plugins-core && \
@@ -25,47 +40,85 @@ RUN dnf -y install dnf-plugins-core && \
     dnf install -y docker-ce-cli && \
     dnf clean all
 
-
 # Configure Git with the GitLab token using BuildKit secret mount
 RUN --mount=type=secret,id=gitlab_token \
     set -eux; \
-    \
     git config --global url."https://oauth2:$(cat /run/secrets/gitlab_token)@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"
 
+# Install Python virtual environment
 ENV VIRTUAL_ENV=/ngencerf/ngencerf-python
-RUN set -eux; \
-	\
-    python3.11 -m venv ${VIRTUAL_ENV}
 ENV PATH=${VIRTUAL_ENV}/bin:${PATH}
+
+RUN set -eux; \
+    python3.11 -m venv ${VIRTUAL_ENV}; \
+    pip3 install --upgrade pip; \
+    # Lock numpy and netcdf4 versions so t-route doesn't break
+    pip3 install "numpy==1.26.4" "pandas~=2.2.2"
 
 WORKDIR /ngencerf/ngencerf-server/
 
-# Install Python virtual environment
+# Install Python requirements
 COPY requirements.txt .
-
 RUN set -eux; \
-    pip3 install -r requirements.txt ; \
-    # Lock numpy and netcdf4 versions so t-route doesn't break
-    pip3 install "numpy==1.26.4" "pandas~=2.2.2" ; \
+    pip3 install -r requirements.txt; \
     rm --force requirements.txt
 
+# Build partitionGenerator
+WORKDIR /ngencerf/ngen-sparse
+RUN --mount=type=secret,id=gitlab_token \
+    set -eux; \
+    # Clone only the required directories
+    git clone --depth 1 --filter=blob:none --sparse https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen.git .; \
+    git sparse-checkout init --cone; \
+    git sparse-checkout set \
+        src \
+        include \
+        extern \
+        cmake; \
+    # Create build directory
+    mkdir -p /ngencerf/partitionGenerator_build; \
+    cd /ngencerf/partitionGenerator_build; \
+    # Configure CMake
+    cmake -DCMAKE_BUILD_TYPE=Release \
+          -DNGEN_WITH_MPI=OFF \
+          -DNGEN_WITH_NETCDF=OFF \
+          -DNGEN_WITH_SQLITE=ON \
+          -DNGEN_WITH_UDUNITS=OFF \
+          -DNGEN_WITH_BMI_FORTRAN=OFF \
+          -DNGEN_WITH_BMI_C=OFF \
+          -DNGEN_WITH_PYTHON=OFF \
+          -DNGEN_WITH_TESTS=OFF \
+          -DNGEN_WITH_ROUTING=OFF \
+          -DNGEN_QUIET=ON \
+          -DNGEN_UPDATE_GIT_SUBMODULES=OFF \
+          -DNGEN_WITH_EXTERN_ALL=OFF \
+          -DNGEN_WITH_EXTERN_SLOTH=OFF \
+          -DCMAKE_BUILD_TYPE=Release \
+          -S /ngencerf/ngen-sparse \
+          -B .; \
+    # Build partitionGenerator
+    cmake --build . --target partitionGenerator -j $(nproc); \
+    # Copy partitionGenerator to server root
+    install -m 755 partitionGenerator /ngencerf/ngencerf-server/; \
+    # Cleanup to reduce image size
+    rm -rf /ngencerf/ngen-sparse /ngencerf/partitionGenerator_build
+
+WORKDIR /ngencerf/ngencerf-server/
+
+# Install additional Python packages
 ARG CREATE_INPUT_TAG
 ARG RUN_SWE_TAG
 ARG CACHE_BUST=1
 # Configure Git with the GitLab token using BuildKit secret mount
 RUN --mount=type=secret,id=gitlab_token \
     set -eux; \
-    \
-    git config --global url."https://oauth2:$(cat /run/secrets/gitlab_token)@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"; \
-    \
-    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-cal.git@${CREATE_INPUT_TAG}#egg=createInput&subdirectory=python/createInput" ; \
-    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-forcing.git@${RUN_SWE_TAG}#egg=swe_processing&subdirectory=swe_processing" ; \
+    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-cal.git@${CREATE_INPUT_TAG}#egg=createInput&subdirectory=python/createInput"; \
+    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-forcing.git@${RUN_SWE_TAG}#egg=swe_processing&subdirectory=swe_processing"; \
     rm --force /root/.gitconfig; \
     pip3 cache purge;
 
 # Should parallel similar functionality in the run_cerf.sh
 COPY .git .git
-# Shoule we move COPY . /ngencerf/ngencerf-server/ to here?  Or up above before the Cache_bust
 
 RUN set -eux; \
     # Get the remote URL from Git configuration
