Final cleanup of docker files

diff --git a/Dockerfile.production-pw b/Dockerfile.production-pw
--- a/Dockerfile.production-pw
+++ b/Dockerfile.production-pw
@@ -1,9 +1,9 @@
 FROM registry.sh.nextgenwaterprediction.com/infrastructure/rockylinux/rockylinux:latest
 
 # Install runtime dependencies
-RUN set -eux; \
-    dnf install -y yum-utils epel-release; \
-    dnf config-manager --set-enabled crb; \
+RUN set -eux && \
+    dnf install -y yum-utils epel-release && \
+    dnf config-manager --set-enabled crb && \
     dnf install -y \
         file \
         findutils \
@@ -17,69 +17,66 @@ RUN set -eux; \
         singularity-ce \
         # The following needed for partitionGenerator
         make \
+        cmake \
         gcc-c++ \
         sqlite-devel \
-        cmake \
-        udunits2 udunits2-devel; \
+        udunits2 udunits2-devel \
+        dnf-plugins-core && \
+    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
+    dnf install -y docker-ce-cli && \
     dnf clean all
 
 # Install Boost 1.79.0 from source
 ARG BOOST_VERSION=1.79.0
 RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-boost \
-    set -eux; \
-    curl --location --output boost.tar.gz "https://archives.boost.io/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz"; \
+    set -eux && \
+    curl --location --output boost.tar.gz "https://archives.boost.io/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz" && \
     mkdir -p /opt/boost && \
     tar --extract --directory /opt/boost --strip-components=1 --file boost.tar.gz && \
     rm boost.tar.gz
 
-ENV BOOST_ROOT=/opt/boost
-
-# Install Docker CLI
-RUN dnf -y install dnf-plugins-core && \
-    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
-    dnf install -y docker-ce-cli && \
-    dnf clean all
-
 # Configure Git with the GitLab token using BuildKit secret mount
 RUN --mount=type=secret,id=gitlab_token \
-    set -eux; \
+    set -eux && \
     git config --global url."https://oauth2:$(cat /run/secrets/gitlab_token)@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"
 
 # Install Python virtual environment
 ENV VIRTUAL_ENV=/ngencerf/ngencerf-python
 ENV PATH=${VIRTUAL_ENV}/bin:${PATH}
 
-RUN set -eux; \
-    python3.11 -m venv ${VIRTUAL_ENV}; \
-    pip3 install --upgrade pip; \
+RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
+    set -eux && \
+    python3.11 -m venv ${VIRTUAL_ENV} && \
     # Lock numpy and netcdf4 versions so t-route doesn't break
-    pip3 install "numpy==1.26.4" "pandas~=2.2.2"
+    pip3 install --upgrade pip "numpy==1.26.4" "pandas~=2.2.2"
 
 WORKDIR /ngencerf/ngencerf-server/
 
-# Install Python requirements
+# Pre-copy requirements for better caching
 COPY requirements.txt .
-RUN set -eux; \
-    pip3 install -r requirements.txt; \
-    rm --force requirements.txt
+
+RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
+    set -eux && \
+    pip3 install -r requirements.txt && \
+    rm -f requirements.txt
 
 # Build partitionGenerator
 WORKDIR /ngencerf/ngen-sparse
 RUN --mount=type=secret,id=gitlab_token \
-    set -eux; \
+    --mount=type=cache,target=/ngencerf/partitionGenerator_build,id=partition-generator-build \
+    --mount=type=cache,target=/root/.cache/cmake,id=cmake-cache \
+    set -eux && \
     # Clone only the required directories
-    git clone --depth 1 --filter=blob:none --sparse https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen.git .; \
-    git sparse-checkout init --cone; \
+    git clone --depth 1 --filter=blob:none --sparse https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen.git . && \
+    git sparse-checkout init --cone && \
     git sparse-checkout set \
         src \
         include \
         extern \
-        cmake; \
-    # Create build directory
-    mkdir -p /ngencerf/partitionGenerator_build; \
-    cd /ngencerf/partitionGenerator_build; \
+        cmake && \
     # Configure CMake
-    cmake -DCMAKE_BUILD_TYPE=Release \
+    cmake -S /ngencerf/ngen-sparse -B /ngencerf/partitionGenerator_build \
+          -DCMAKE_BUILD_TYPE=Release \
           -DNGEN_WITH_MPI=OFF \
           -DNGEN_WITH_NETCDF=OFF \
           -DNGEN_WITH_SQLITE=ON \
@@ -93,15 +90,13 @@ RUN --mount=type=secret,id=gitlab_token \
           -DNGEN_UPDATE_GIT_SUBMODULES=OFF \
           -DNGEN_WITH_EXTERN_ALL=OFF \
           -DNGEN_WITH_EXTERN_SLOTH=OFF \
-          -DCMAKE_BUILD_TYPE=Release \
-          -S /ngencerf/ngen-sparse \
-          -B .; \
+          -DBOOST_ROOT=/opt/boost && \
     # Build partitionGenerator
-    cmake --build . --target partitionGenerator -j $(nproc); \
+    cmake --build /ngencerf/partitionGenerator_build --target partitionGenerator --parallel && \
     # Copy partitionGenerator to server root
-    install -m 755 partitionGenerator /ngencerf/ngencerf-server/; \
-    # Cleanup to reduce image size
-    rm -rf /ngencerf/ngen-sparse /ngencerf/partitionGenerator_build
+    install -m 755 /ngencerf/partitionGenerator_build/partitionGenerator /ngencerf/ngencerf-server/ && \
+    # Cleanup non-cached build artifacts
+    rm -rf /ngencerf/ngen-sparse
 
 WORKDIR /ngencerf/ngencerf-server/
 
@@ -111,23 +106,23 @@ ARG RUN_SWE_TAG
 ARG CACHE_BUST=1
 # Configure Git with the GitLab token using BuildKit secret mount
 RUN --mount=type=secret,id=gitlab_token \
-    set -eux; \
-    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-cal.git@${CREATE_INPUT_TAG}#egg=createInput&subdirectory=python/createInput"; \
-    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-forcing.git@${RUN_SWE_TAG}#egg=swe_processing&subdirectory=swe_processing"; \
-    rm --force /root/.gitconfig; \
-    pip3 cache purge;
+    set -eux && \
+    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-cal.git@${CREATE_INPUT_TAG}#egg=createInput&subdirectory=python/createInput" && \
+    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-forcing.git@${RUN_SWE_TAG}#egg=swe_processing&subdirectory=swe_processing" && \
+    rm -f /root/.gitconfig && \
+    pip3 cache purge
 
 # Should parallel similar functionality in the run_cerf.sh
 COPY .git .git
 
-RUN set -eux; \
+RUN set -eux && \
     # Get the remote URL from Git configuration
-    repo_url=$(git config --get remote.origin.url); \
+    repo_url=$(git config --get remote.origin.url) && \
     # Extract the repo name (everything after the last slash) and remove any trailing .git
-    key=${repo_url##*/}; \
-    key=${key%.git}; \
+    key=${repo_url##*/} && \
+    key=${key%.git} && \
     # Construct the file path using the derived key
-    GIT_INFO_PATH="${key}_git_info.json"; \
+    GIT_INFO_PATH="${key}_git_info.json" && \
     jq -n \
       --arg commit_hash "$(git rev-parse HEAD)" \
       --arg branch "$(git rev-parse --abbrev-ref HEAD)" \
@@ -143,7 +138,7 @@ RUN set -eux; \
 COPY . /ngencerf/ngencerf-server/
 
 # Remove .git directory
-RUN rm --recursive --force .git
+RUN rm -rf .git
 
 # Copy additional configuration files
 COPY ./cerfserver-docker.env /ngencerf/ngencerf-server/cerfserver.env
